# Generated by Django 4.0.1 on 2022-04-18 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_users_clients'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Clients',
            new_name='Users',
        ),
    ]
