# Generated by Django 4.0.1 on 2022-04-18 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_clients_users'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='Clients',
        ),
    ]
