# Generated by Django 4.0.1 on 2022-04-18 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_clients_contacts_clients_contacts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='contacts',
            field=models.ManyToManyField(blank=True, to='users.Clients'),
        ),
    ]
