# Generated by Django 4.0.1 on 2022-04-18 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_clients_chats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clients',
            name='chats',
        ),
    ]
