# Generated by Django 4.0.1 on 2022-04-18 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0007_alter_clients_contacts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('chat_id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('chat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chats.chat')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.clients')),
            ],
        ),
        migrations.AddField(
            model_name='chat',
            name='message_list',
            field=models.ManyToManyField(blank=True, related_name='message_ids', to='chats.Messages'),
        ),
        migrations.AddField(
            model_name='chat',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='Members', to='users.Clients'),
        ),
    ]
